export const UI = {
	DRAG_THRESHOLD: 5,
	RESIZE_HANDLE_SIZE: 8,
	ZOOM_STEP: 0.05,
	FILTER: {
		BLUR_MIN: 0,
		BLUR_MAX: 10,
		BLUR_STEP: 0.5,
		THRESHOLD_MIN: 0,
		THRESHOLD_MAX: 255,
	},
	DEBOUNCE_DELAY_MS: 150,
};
